- name: Vérifier la configuration des adresses IP
  hosts: all
  gather_facts: yes
  vars:
    ip_addresses:
      - 192.168.56.104
      - 192.168.43.129
      - 10.0.3.15
  tasks:
    - name: Obtenir les informations sur les interfaces réseau
      command: ip a
      register: ip_output
      changed_when: false
    - name: Analyser les adresses IP
      set_fact:
        configured_ip_addresses: "{{ ip_output.stdout | regex_findall('inet [0-9],[0-9],[0-9],[0-9]') }}"
      changed_when: false
      debug:
        msg: configured_ip_addresses
    - name: Vérifier les adresses IP configurées
      debug:
        msg: "L'adresse IP {{ item }} n'est pas correctement configurée."
      loop: "{{ ip_addresses }}"
      when: item not in configured_ip_addresses
