# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 127.0.0.1
  become: yes

  tasks:

- name: Call Roles
  hosts: 127.0.0.1
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
