---
- name: Check if user can run specific commands
  hosts: 192.168.43.114
  become: true
  vars:
    commands:
      - /bin/ls
      - /bin/ping
      - /bin/cd

  tasks:
    - name: Check if user can run commands
      shell:
        cmd: "sudo -l -U orange | grep 'NOPASSWD: {{ item }}'"
        warn: no
        ignore_errors: yes
      loop: "{{ commands }}"
      register: result

    - name: Print results
      debug:
        var: result

    - name: Check results
      assert:
        that:
          - "'not allowed to run' not in item.stderr"
        fail_msg: "User orange cannot run command '{{ item.item }}' with sudo"
      loop: "{{ result.results }}"
