---
- name: check if all permissions needed are granted to the user orange
  hosts: 192.168.43.129
  become: true
  gather_facts: false 
  vars:
    user: orange
    commands:
       - /bin/ls
       - /bin/ping
       - /bin/cd
       - /usr/sbin/viduso
  tasks:
    - name: check sudoers
      command: "sudo -l -U '{{ user }}'"
      register: result
      ignore_errors: yes 
    - name: Print sudoers configuration
      debug:
       var: result.stdout_lines
    - name: Check for command permission
      assert:
        that:
          - "'{{ user }}' in result.stdout_lines"
          - "'(ALL : ALL) NOPASSWD: ALL' in result.stdout_lines"
          - "'{{ user }} ALL=(ALL) NOPASSWD: {{ commands | join(\",\") }}' in result.stdout_lines"
          fail_msg: "'{{ user }}' is not allowed to run '{{ commands }}' with sudo permission"
      when: commands is defined
