---
- name: Check if user can run specific commands
  hosts: 192.168.43.129
  become: true
  vars:
    commands:
      - ls
      - ping
      - cd
  tasks:
    - name: Check if user can run commands
      shell:
        cmd: "sudo -l -U orange | grep 'NOPASSWD:' | awk '!/{{ item }}/ print 'orange user can not run {{ item }} ''"
      loop: "{{ commands }}"
      register: result
    - name: Print results
      debug:
        var: result
