---
- name: Check if user can run specific commands
  hosts: all
  become: true
  vars:
    commands:
      - ls
      - ping
      - ip
      - cat
  tasks:
    - name: Check if user can run commands
      shell: sudo -l -U orange | grep '(root)' | awk '!/{{ item }}/ {print "orange user can not run {{ item }}" }'
      loop: "{{ commands }}"
      register: result
    - name: Print results
      debug:
        var: result.results|map(attribute='stdout')|select('match','^orange')|list
