---
- name: Check if user can run specific commands
  hosts: 192.168.43.114
  become: true
  vars:
    commands:
      - ls
      - ping
      - ll

  tasks:
    - name: Check if user can run commands
      assert:
        that:
          - item.rc == 0
          - "'orange' in item.stdout"
        fail_msg: "User orange cannot run command '{{ item.item }}' with sudo"
      loop: "{{ commands }}"
      register: result

    - name: Print results
      debug:
        var: result
